node {
   def commit_id
   stage('clone repo') {
        checkout scm
        sh "git rev-parse --short HEAD > .git/commit-id"                        
        commit_id = readFile('.git/commit-id').trim()
   }

   stage('install libs') {
        steps {
            sh 'pip install pytest'
        }
   }

    stage('tests') {
        steps {
            sh 'pytest -v ./tests/'
        }
   }

   stage('docker build/push') {
        docker.withRegistry('https://index.docker.io/v2/', 'dockerhub') {
        def app = docker.build("sunlnx/demo-fastapi:${commit_id}", '.').push()
        }
   }
}