name: python application
on:
    push:
        branches: 
          - develop
jobs:
    preinstall:
        runs-on: ubuntu-latest
        steps:
            - name: repository checkout
              uses: actions/checkout@v3

            - name: python3.10 setup 
              uses: actions/setup-python@v4
              with:
                python-version: '3.10'
                check-latest: true

            - name: install dependencies
              run: |
                pip install fastapi["all"]
                if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

            - name: install flake8
              run: |
                flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

            - name: test with pytest
              run: |
                pytest   