name: ci
on:
    pull_request:
        branches: 
          - develop
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: repository checkout
              uses: actions/checkout@v3

            - name: python3.10 setup 
              uses: actions/setup-python@v4
              with:
                python-version: '3.10'
                check-latest: true

            - name: install dependencies
              run: |
                pip install fastapi["all"]
                if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

            - name: linting
              run: flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

            - name: run testcases
              run: pytest

            - name: test coverage report
              run: pytest --cov=./app ./tests
              