name: python application
on:
    push:
        branches: ["master"]
jobs:
    checkout:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: python3.10 setup 
              uses: actions/setup-python@v4
              with:
                python-version: '3.10'
                check-latest: true

    install_libs:
        runs-on: ubuntu-latest
        steps:
            - name: install dependencies
              run: |
                pip install fastapi["all"]
                if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            - name: install flake 
              run: |
                flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
            - name: test with pytest
              run: |
                pytest   